Feat/styling
TobiAugust/capstone-project pull request #13
Opened 2023-06-15 14:03 UTC by TobiAugust

Change styling and add the input Person

2023-06-15 16:01 UTC, MerleMak requested changes
Hello Tobias, i left you a bunch of comments and recommendations. I like the new styles. But you definitely need to get rid of most of your useStates :)
I am excited for the updates! 😊

2023-06-16 13:41 UTC, TobiAugust commented on components/Footer.js
> +  margin-top: 40px;
Do I have to write margin: fixed or how can I implement your idea?

2023-06-16 13:53 UTC, TobiAugust commented on components/FooterLink.js
> +  color: #333;
Accepted and implemented

2023-06-16 13:56 UTC, TobiAugust commented on components/Form.js
> +  margin-bottom: 10px;
for the moment I don´t see it nessesary but I will change it in future

2023-06-16 14:02 UTC, TobiAugust commented on components/StyledInput.js
> +  box-shadow: 0px 1px 7px 4px rgba(0, 0, 0, 0.25);
<img width="355" alt="Bildschirm­foto 2023-06-16 um 16 01 12" src="https://github.com/TobiAugust/capstone-project/assets/128328381/7fcd98bb-a51e-4a83-8a89-d7a74dc1b2d6">

here on my picture I see the Shadow?

2023-06-16 14:11 UTC, TobiAugust commented on components/TaskItem.js
> +  box-shadow: 0px 10px 13px -7px #000000, 5px 5px 15px 5px rgba(0, 0, 0, 0);
good idea, accepted and implemented but now It looks like the taskItem lays on a white card. can I change it that way, the "white card could be removed?"
<img width="341" alt="Bildschirm­foto 2023-06-16 um 16 11 20" src="https://github.com/TobiAugust/capstone-project/assets/128328381/f59c38b1-10a8-4f22-b7a8-d3883677d311">

2023-06-16 14:12 UTC, TobiAugust commented on components/TaskItem.js
> +const TaskItemContainer = styled.div`
True and implemented

2023-06-16 14:14 UTC, TobiAugust commented on components/TaskItem.js
> +const TaskTitle = styled.p`
yeah thats right, but as a p-tag I can change the bold of the sentence, what I created some words are bold and some solid. with the h2 tag everything is bold and that looks bad

2023-06-16 14:26 UTC, TobiAugust commented on pages/index.js
> +  const [personInput, setPersonInput] = useState("");
I used for that problem now formData to implent the facts person, task, date to delete all the useStates I dont need and setData to actualize the Data

2023-06-16 14:28 UTC, TobiAugust commented on pages/index.js
> +              date: selectedDate,
yes you are right^^

2023-06-16 14:43 UTC, TobiAugust commented on components/InputBox.js
> +const InputBox = styled.div`
accepted and changed

2023-06-16 14:44 UTC, TobiAugust commented on pages/index.js
> +                  <Label htmlFor="date">
accepted and changed

2023-06-20 18:36 UTC, merged